# Generated by Django 4.2.2 on 2023-06-29 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company', to=settings.AUTH_USER_MODEL),
        ),
    ]
