# Generated by Django 4.2.2 on 2023-06-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_initial'),
        ('personal', '0002_customuser_first_name_customuser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('id', 'department')},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fio',
        ),
    ]
