# Generated by Django 4.2.2 on 2023-06-29 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_initial'),
        ('personal', '0003_alter_customuser_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='department.department'),
        ),
    ]
